### ISSUE TITLE
Can't Develop Locally

### ISSUE THREAD

**Issue by sdale28** [HabitRPG/habitica-ios#419]
Hi there. I've been trying to get setup locally, but I can't get past the installation of cocoapods. I get cocoapods installed, but then when I go to do the ```pod install``` I get an error saying I don't have 
cocoapods-keys installed like in https://github.com/HabitRPG/habitica-ios/issues/416

So I do this and it still doesn't work: 

```
~ habitica-ios $ sudo gem install cocoapods-keys
Successfully installed cocoapods-keys-1.7.0
Parsing documentation for cocoapods-keys-1.7.0
1 gem installed
~ habitica-ios $ pod install

---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.

LoadError - cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:94:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:94:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.
```

Any help would be appreciated.

**Comment by schomes** [comment]
You may need to update the read permissions for /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0. To do this, execute 

`sudo chmod -R go+r /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0`

Now try running `pod install` again.
